name: Build ConsoleApp project

on:
  push:
    branches-ignore:
      - 'dependabot/**'

  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['6.0.x']

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup .NET SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
          
      - name: Install dependencies
        run: dotnet restore
        
      - name: Build
        run: dotnet build --configuration Release --no-restore
        
      - name: Run unit tests
        run: dotnet test --no-restore --verbosity normal

      - name: Install Resharper CLR
        uses: kasperhesthaven/setup-resharper-clt@v1.1.0
        with:
          resharper-version: "2022.1.2"

      - name: Clean up code
        run: cleanupcode.sh Simple.ConsoleApp.Template.sln

      - name: Analyze code
        run: inspectcode.sh Simple.ConsoleApp.Template.sln -o=TestAnalysis.xml
        