name: Test Baseline Input Parameters Workflow

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version Number"  # Description for the input parameter
        required: true  # Set to true if the input is mandatory
        default: "1.0.0.0"  # Default value if no input is provided
      baselinemessage:
        description: "Baseline Message" #Description for the input parameter
        required: true #set to true if the input is madatory
        default: "Baselining"

jobs:
  printinputparmeters:
    runs-on: ubuntu-latest

    steps:
      - name: Print Version Number
        run: echo "Version number is ${{ github.event.inputs.version }}!"

      - name: Print Baseline Message
        run: echo "Baseline message is ${{ github.event.inputs.baselinemessage  }}"
